### ISSUE TITLE
Sampling Rate Question

### ISSUE THREAD

**Issue by nikhilramachandra** [mich11/multi-band-integrator#1]
Hi,

I have a question about the sampling rate of the multi-band integrator. 
Is the power calculated and returned at the same sampling rate being used for open ephys?
For example, if I am sampling in open ephys at 30,000Hz, and I am using the multi-band integrator with the crossing detector, with the crossing detector set so that 50% of the previous 30,000 power signal samples must be above the threshold, does this mean half of the power signal values in the last 1 second must be above the threshold?

Best,

Nikhil

**Comment by mich11** [comment]
Hi,

Sorry for the delayed response.  Yes, the output signal is calculated and
returned at the same sampling rate as the sampling rate set on open ephys's
rhythm FPGA.  In your example, you are correct that 50% of the output
values from the multi-band integrator over the last 1s would need to be
above the threshold.  The multi-band integrator also applies a rolling
average, so it can also tell you something about the previous 1s if that's
useful for your waveform detection.

Best,
Michelle

On Tue, Jul 10, 2018 at 9:24 AM, nikhilramachandra <notifications@github.com
